Convert RBGL.Rnw to RBGL.Rmd
Bioconductor/RBGL pull request #3
Opened 2023-03-21 10:26 UTC by devbird007

@Bioconductor/sweave2rmd
I am an Outreachy Applicant, please review my pull request.

@jwokaty Hello, I have converted the RBGL.Rnw file to Rmd. Kindly review my PR.
The PDF and HTML files for comparison:
[RBGL.pdf](https://github.com/Bioconductor/RBGL/files/11027093/RBGL.pdf)
[RBGL.html](https://rpubs.com/devbird007/1025685)

I have reviewed it myself with the Checklist and made sure it was able to build successfully with `R CMD build`.
I also ensured to wrap word lines, leave a carriage line before & after the code chunks and properly reference Bioconductor packages. So I reasonably believe it will take a short time to complete the review process before merging.

Also, I noticed the positioning of some Figures in the vignettes to be improper and took the initiative to rectify this. One example is to compare `Figure4`'s position in the PDF and HTML files.

2023-03-23 08:00 UTC, devbird007 commented
Hi @jwokaty , I woke up today and went through the checklist again to another review:

- [ ] the `.Rmd` file knits to `HTML`
- [ ] `R CMD build` runs without errors or timeouts
- [ ] the tarball from `R CMD build` contains the `HTML` (check with the
  following by substituting the package name and vignette name `tar ztf
  package_name.tar.gz | grep 'doc/vignette_name'`)
- [ ] the `.Rnw` file has been removed
- [ ] in the `DESCRIPTION`, `BiocStyle` and `knitr` are listed in `Suggests`
- [ ] in the `DESCRIPITON`, the line `VignetteBuilder: knitr` exists
- [ ] any added lines use the same spacing and indents as the existing
  document
- [ ] if agreed with the Maintainer, the contributor is in the author list
  in the `DESCRIPTION` file; refer to the contribution guide for acceptable
  formats
- [ ] if agreed with the Maintainer, the contributor is in the author list
  in the vignette's YAML; refer to the contribution guide for acceptable formats
- [ ] if this pull request includes a conversion from using the separate `Author`
  and `Maintainer` lines into the `Authors@R` vector, check that the
  `Authors@R` vector includes the maintainer as specified with `role='cre'`.
- [ ] if this pull request includes a conversion from using the separate `Author`
  and `Maintainer` lines into the `Authors@R` vector, the `Maintainer` line
  is completely removed.
- [ ] `HTML` document is representative of the `PDF` in content and
  in general the presentation
- [ ] Where the contributor was not able to preserve the content and presentation
  of the `PDF` is noted as a comment in the pull request
- [ ] the R Markdown file is representative of the Sweave document and follows
  best practices, such as replacing links to Bioconductor packages with calls
  to BiocStyle's `Biocpkg()`

2023-03-26 07:06 UTC, devbird007 commented
@jwokaty I decided to publish my generated HTML file on RPubs and linking it in the first comment, I figured this is more efficient than uploading a zipped HTML file like I did in my last PR.

2023-03-27 16:14 UTC, villafup requested changes
This is a preliminary review.  Nice work overall.  I noticed that a couple of graphs are out of place.  Some of them appear in the original vignette between code chunk outputs.  I don't think we can change that behavior, so please leave as is and make a note to that effect.

2023-03-27 16:14 UTC, villafup commented on vignettes/RBGL.Rmd
> +## Basics Notations
It may not be possible, but see if you can get this summary to appear before the TOC.  You can google "YAML" options.  [This ](https://cran.r-project.org/web/packages/ymlthis/vignettes/yaml-fieldguide.html)and [this](https://bookdown.org/yihui/bookdown/yaml-options.html) might be helpful

2023-03-27 16:14 UTC, villafup commented on vignettes/RBGL.Rmd
> +  %\VignetteEncoding{UTF-8}
Vignette Index Entry shoud be `VignetteIndexEntry{RBGL Overview}`  Aso add lines 

```
%\VignetteDepends{graph}
%\VignetteKeywords{Graphs}
```

These should be carried over from the Rnw

2023-03-27 16:14 UTC, villafup commented on vignettes/RBGL.Rmd
> +```{r, fig.cap = "The example graphs (I).", fig.height = 8, echo = FALSE}
Let's see if a carriage return right before here improves readability.  If that would have any affect at all ...

2023-03-27 16:14 UTC, villafup commented on vignettes/RBGL.Rmd
> +```{r, fig.cap = "The example graphs (II).", fig.height = 8, echo = FALSE}
Carriage return here

2023-03-27 16:14 UTC, villafup commented on vignettes/RBGL.Rmd
> +```{r, fig.cap = "The example graphs (III).", fig.height = 8, echo = FALSE}
Carriage return

2023-03-27 16:14 UTC, villafup commented on vignettes/RBGL.Rmd
> +plot(ospf)
Move the code chunk that produces the graph before the paragraph "The first part of ..." as in original vignette.

2023-03-27 16:14 UTC, villafup commented on vignettes/RBGL.Rmd
> +
Missing figure 8 from original vignette (page 16)

2023-03-27 16:14 UTC, villafup commented on vignettes/RBGL.Rmd
> +
Missing `Figure 9: Kruskal MST examples` from original vignette (page 18).  I think you have it at line 415.

2023-03-27 16:14 UTC, villafup commented on vignettes/RBGL.Rmd
> +There are 4 biconnected components in the example: one with vertices *B, C, D*
The graph from line 457 conflicts with the original vignette, but in the original pdf it appears in the middle of output from a code block.  I'm mentioning as a difference between this output and the pdf.

2023-03-27 16:14 UTC, villafup commented on vignettes/RBGL.Rmd
> +```
In the original pdf, this graph appears between a code block and its output.  Noting as a difference between original and converted.  I do not think it's possible to correct.

2023-03-27 16:14 UTC, villafup commented on vignettes/RBGL.Rmd
> +```
Move graph before parapgraph that begins "We need 4 colors ..." (line 628

2023-03-27 16:14 UTC, villafup commented on vignettes/RBGL.Rmd
> +```
Appears in the middle of chunk output in original vignette

2023-03-27 16:14 UTC, villafup commented on vignettes/RBGL.Rmd
> +```
Appears in the middle of code chunk output in original vignette

2023-03-29 03:40 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +## Basics Notations
Hello @villafup , I spent lots of hours on this and wasn't able to make any progress, using the resources you linked and doing my own research, the best I could do was get it up above all the texts as indicated in the image below. Even prior to making my PR, I had asked a question on this particular issue in the Slack channel and Jen's comment was to try my best and leave it as is, since it's always possible to do a one-to-one conversion. Here is a link to the [comment](https://community-bioc.slack.com/archives/C03E7TWE2NT/p1679325086931589?thread_ts=1679273306.000699&cid=C03E7TWE2NT).

![Screenshot from 2023-03-28 09-19-57](https://user-images.githubusercontent.com/100073682/228420842-abd9843d-d8bc-4db2-9ac8-b6f422747e0f.png)

2023-03-29 03:46 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +  %\VignetteEncoding{UTF-8}
Done

2023-03-29 04:35 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +```{r, fig.cap = "The example graphs (I).", fig.height = 8, echo = FALSE}
Done. Though I am not sure it has had the intended effect.

2023-03-29 04:35 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +```{r, fig.cap = "The example graphs (II).", fig.height = 8, echo = FALSE}
Done

2023-03-29 04:35 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +```{r, fig.cap = "The example graphs (III).", fig.height = 8, echo = FALSE}
Done

2023-03-29 04:38 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +plot(ospf)
Done so.

2023-03-29 04:38 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +
Done, Figure 8 was higher in the text than it should have been and I have moved it accordingly.

2023-03-29 04:40 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +
Done. The reason I think this is happening is that, after running the `pandoc` command, I edited the code blocks in place and didn't move them to a different position in a way that would align with the PDF output.

The code chunk to plot `Figure 9: Kruskal MST examples` depends on the `conndemo` code chunk in the `## Connected components` subsection, So I have repositioned it according to your comment and referred the `conndemo` code chunk inside of it too.

2023-03-29 04:43 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +There are 4 biconnected components in the example: one with vertices *B, C, D*
Understood.

2023-03-29 04:43 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +```
Agreed.

2023-03-29 04:44 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +```
Done

2023-03-29 18:54 UTC, villafup commented
**DESCRIPTION**

- [ ]  in the `DESCRIPTION`, `BiocStyle` and `knitr` are listed in `Suggests`
- [ ]  in the `DESCRIPITON`, the line `VignetteBuilder: knitr` exists
- [ ]  if agreed with the Maintainer, the contributor is in the author list in the `DESCRIPTION` file; refer to the contribution guide for acceptable formats
- [ ] if agreed with the Maintainer, the contributor is in the author list in the vignette's YAML; refer to the contribution guide for acceptable formats
- [ ] if this pull request includes a conversion from using the separate `Author` and `Maintainer` lines into the `Authors@R` vector, check that the `Authors@R` vector includes the maintainer as specified with `role='cre'`.
- [ ] if this pull request includes a conversion from using the separate `Author` and `Maintainer` lines into the `Authors@R` vector, the `Maintainer` line is completely removed.

**Rmd**

- [ ]  any added lines use the same spacing and indents as the existing document
- [ ] the `.Rmd` file knits to `HTML`
- [ ] `HTML` document is representative of the `PDF` in content and in general the presentation
- [ ]  Where the contributor was not able to preserve the content and presentation of the `PDF` is noted as a comment in the pull request
- [ ]  the R Markdown file is representative of the `PDF` of the Sweave document and follows best practices, such as replacing links to Bioconductor packages with calls to BiocStyle's `Biocpkg()`

**Rnw**

- [ ]  the `.Rnw` file has been removed

**Package Build**

- [ ] `R CMD build` runs without errors or timeouts
- [ ] the tarball from `R CMD build` contains the `HTML` (check with the following by substituting the package name and vignette name `tar ztf package_name.tar.gz | grep 'doc/vignette_name'`)

2023-03-29 21:05 UTC, villafup requested changes
I appreciate your efforts on looking into the placement of the Summary section.

In addition to these few changes, could you also please note here where you (1) could not change the placement of the graphs to match the pdf, and (2), make a note about where you had to rearrange code chunks to get the graphs to render.  You have already made most of these, but if we could have something like "Note from Converter: blah blah" so we have a note from you.

And can you confirm that the package build (R CMD build and grep) work as expected?

2023-03-29 21:05 UTC, villafup commented on DESCRIPTION
> +                comment = "'RBGL' vignette translation from Sweave to RMarkdown / HTML."),
Please follow the exact phrasing found in the Contribute document

2023-03-29 21:05 UTC, villafup commented on vignettes/RBGL.Rmd
> +```{r, fig.cap = "The example graphs (II).", fig.height = 8, echo = FALSE}
There should only be 1 carriage return between sections. I'm sorry if I indicated something else.

2023-03-29 21:05 UTC, villafup commented on vignettes/RBGL.Rmd
> +```{r, fig.cap = "The example graphs (III).", fig.height = 8, echo = FALSE}
Remove carriage return

2023-03-29 21:05 UTC, villafup commented on vignettes/RBGL.Rmd
> +<<conndemo>>
Is this needed?  I think we can remove.

2023-03-30 08:24 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +```{r, fig.cap = "The example graphs (II).", fig.height = 8, echo = FALSE}
Oh I understand now, I have fixed all the instances that were altered back to 1 carriage return.

2023-03-30 08:24 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +```{r, fig.cap = "The example graphs (II).", fig.height = 8, echo = FALSE}
Oh I understand now, I have fixed all the instances that were altered back to 1 carriage return.

2023-03-30 08:24 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +```{r, fig.cap = "The example graphs (III).", fig.height = 8, echo = FALSE}
Fixed

2023-03-30 08:32 UTC, devbird007 commented on DESCRIPTION
> +                comment = "'RBGL' vignette translation from Sweave to RMarkdown / HTML."),
Sorry about that, fixed it now...

2023-03-30 08:34 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +<<conndemo>>
The graph wouldn't plot without the `<<conndemo>>` line.

Or maybe you are referring to something else that I should remove?

2023-04-03 10:00 UTC, devbird007 commented
> I appreciate your efforts on looking into the placement of the Summary section.
> 
> In addition to these few changes, could you also please note here where you (1) could not change the placement of the graphs to match the pdf, and (2), make a note about where you had to rearrange code chunks to get the graphs to render. You have already made most of these, but if we could have something like "Note from Converter: blah blah" so we have a note from you.
> 
> And can you confirm that the package build (R CMD build and grep) work as expected?

Hi @villafup , I have spent a few days redoing the entire thing because I haven't been able to quite understand what the note should look like, could you please explain more on it?

There were code chunks for graphs that did not render at all, and there were code chunks for graphs that appeared a couple of lines away (like after a paragraph instead of before it) after I ran the `pandoc` command. I have been trying to redo the entire thing by leaving the graph code chunks in their place but with the `echo = FALSE` & `eval = FALSE` parameters so they don't run at all.

Then anytime I need a graph to render I create a new code block and reference the ones I forced to not render with the `<<chunk_name>>` syntax like I did in this [comment](https://github.com/Bioconductor/RBGL/pull/3#discussion_r1152922236).

Further information clarifying what you want me to do exactly would be appreciated.

2023-04-05 18:13 UTC, villafup commented
In the conversation for the pull request, any time the pdf does not match your knitted file, add:

2023-04-06 20:20 UTC, jwokaty commented on vignettes/RBGL.Rmd
> +## Basics Notations
Regarding the summary--and I wish there was a better yaml header resource and I regret not trying to this immediately--I think we can just add in the yaml header. It's okay that it doesn't follow the same order as the PDF.

    ---
    title: "*RBGL*: R interface to boost graph library"
    author:
    - name: "L. Long"
    - name: "VJ Carey"
    - name: "R. Gentleman"
    - name: "Emmanuel Taiwo"
      affiliation: "Vignette translation from Sweave to R Markdown / HTML"
    date: "`r format(Sys.time(), '%B %d, %Y')`"
    vignette: >
      %\VignetteEngine{knitr::rmarkdown}
      %\VignetteIndexEntry{RBGL Overview}
      %\VignetteDepends{graph}
      %\VignetteKeywords{Graphs}
      %\VignettePackage{RBGL}
      %\VignetteEncoding{UTF-8}
    output:
      BiocStyle::html_document:
        number_sections: yes
        toc: yes
        toc_depth: 4
    summary:  >
      The `r Biocpkg("RBGL")` package is primarily an interface
      from R to the Boost Graph Library (BGL). It includes some graph
      algorithms built on top of those from BGL and some algorithms
      independent of BGL.
    ---

2023-04-07 17:43 UTC, devbird007 commented
Hello @villafup @jwokaty 

I know I was asked to make a note every time the pdf doesn't match the knitted file.
But instead I've spent the last few days rewriting the file to match the figures in the PDF file.

The only ones I couldn't match were those that appeared in the middle of a code output, and for those I placed the image immediately after the code output.

Forgive me if I may be creating more work for you by making you go over it all over again, I will commit the new changes now.

Do let me know what you would want me to do next.

2023-04-11 03:59 UTC, jwokaty commented on vignettes/RBGL.Rmd
> +```{r fdpic, fig.cap = "File dependency digraph example from Boost", fig.height = 7, results = "hide", echo = FALSE}
Just missing the word `library` after `Boost`

2023-04-11 04:20 UTC, jwokaty commented on vignettes/RBGL.Rmd
> +```{r tsortDemo2}
Let's add `warning=FALSE` to prevent the warning from showing up.

2023-04-11 04:43 UTC, jwokaty commented on vignettes/RBGL.Rmd
> +
I believe this is cruft. It's unrelated to the section before and after it. Could I ask you to please remove it?

For documentation purposes, I'll note that it appears to have been introduced in [Bioc 2.9](https://bioconductor.org/packages/2.9/bioc/vignettes/RBGL/inst/doc/RBGL.pdf) and didn't exist in [Bioc 2.8](https://bioconductor.org/packages/2.8/bioc/vignettes/RBGL/inst/doc/RBGL.pdf).

2023-04-11 05:06 UTC, jwokaty commented on vignettes/RBGL.Rmd
> +if edge *f(u) -> f(v)* exists and is in *E(g2)*.
I think the `if` on line 677 should be `iff`, which means "if and only if" and is used as a shorthand in mathematical definitions.

2023-04-11 05:10 UTC, jwokaty commented on vignettes/RBGL.Rmd
> +Steiglitz: G is chordal if either G is an empty graph, or there is a
`if` should be `iff` ("if and only if" shorthand).

2023-04-11 05:19 UTC, jwokaty commented on vignettes/RBGL.Rmd
> +whole graph is N-clique.
This should be a paragraph and a list (the `o.`'s are supposed to be the bullets) but I think no one noticed for a few Bioconductor versions. Could I ask you to help us make it right by reformatting lines 903-910. You can see the corresponding section at https://github.com/Bioconductor/RBGL/pull/3/files#diff-237d0241313835709877d45b6627d8f5867fec1580cd6a9da4c6068709063f98L1169-L1178 to guide you. You don't have to use the `o.` bullet, just make it the way you would with R Markdown if that makes sense.

2023-04-11 05:24 UTC, jwokaty requested changes
Good work. This was a really long, difficult vignette with a few areas that old code went unnoticed.

I just have a few changes to improve the vignette. When you submit the changes, I'll just review those sections, make sure it R CMD builds, and merge. Thanks.

2023-04-11 07:16 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +```{r fdpic, fig.cap = "File dependency digraph example from Boost", fig.height = 7, results = "hide", echo = FALSE}
Fixed, sorry I don't know how I missed that.

2023-04-11 07:17 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +```{r tsortDemo2}
Fixed

2023-04-11 07:19 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +
Duly noted, and yes I have removed it now.

2023-04-11 07:24 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +if edge *f(u) -> f(v)* exists and is in *E(g2)*.
Fixed. I understand that now and will keep it in mind for future vignettes I may work on.

2023-04-11 07:24 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +if edge *f(u) -> f(v)* exists and is in *E(g2)*.
Fixed. I understand that now and will keep it in mind for future vignettes I may work on.

2023-04-11 08:04 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +Steiglitz: G is chordal if either G is an empty graph, or there is a
Fixed, working on this vignette helped me understand that I really should just focus on replicating it exactly as it is in the PDF, because I had assumed the `iff`s were typos.

2023-04-11 08:10 UTC, devbird007 commented on vignettes/RBGL.Rmd
> +whole graph is N-clique.
Fixed.

2023-04-11 08:25 UTC, devbird007 commented
> Good work. This was a really long, difficult vignette with a few areas that old code went unnoticed.
> 
> I just have a few changes to improve the vignette. When you submit the changes, I'll just review those sections, make sure it R CMD builds, and merge. Thanks.

After fixing the unordered list, I noticed that lines `319-338` contain a few lists, would you also like me to align them?
I also observed that lines `796` and `817` have a citations, I would also like to try to fix those.

I have also confirmed that it builds successfully

2023-04-12 03:33 UTC, jwokaty commented
> After fixing the unordered list, I noticed that lines `319-338` contain a few lists, would you also like me to align them? I also observed that lines `796` and `817` have a citations, I would also like to try to fix those.

Are you referring to https://github.com/Bioconductor/RBGL/pull/3/files#diff-237d0241313835709877d45b6627d8f5867fec1580cd6a9da4c6068709063f98L365-L375? Then yes. I think there might be another a few lines below that. Thanks for catching those.

I noticed the references are inline. I think they're okay as they are as there wasn't a reference section at the end of the document in older versions if I remember the correctly.

2023-04-12 12:01 UTC, devbird007 commented
> > After fixing the unordered list, I noticed that lines `319-338` contain a few lists, would you also like me to align them? I also observed that lines `796` and `817` have a citations, I would also like to try to fix those.
> 
> Are you referring to https://github.com/Bioconductor/RBGL/pull/3/files#diff-237d0241313835709877d45b6627d8f5867fec1580cd6a9da4c6068709063f98L365-L375? Then yes. I think there might be another a few lines below that. Thanks for catching those.
> 
> I noticed the references are inline. I think they're okay as they are as there wasn't a reference section at the end of the document in older versions if I remember the correctly.

Hi @jwokaty, the link you placed in your comment doesn't link to actual lines in the file so I don't quite know what you might be referring to.

But, I have made the lists where I saw fit, do let me know if you would like me to reverse them back to normal I worry I might have overdid it.

2023-04-12 22:43 UTC, jwokaty commented
> Hi @jwokaty, the link you placed in your comment doesn't link to actual lines in the file so I don't quite know what you might be referring to.

You have to click on `Load diff` on the .Rnw to see the lines the link highlights.

I'll try to look at it later today or tomorrow.

2023-04-13 12:17 UTC, devbird007 commented
> You have to click on `Load diff` on the .Rnw to see the lines the link highlights.
> 
> I'll try to look at it later today or tomorrow.

Thanks for clarifying, I was able to find the section and make the changes there. I also made changes to two other sections that looked like they should be lists. They were carrying `(a)...` and `(i)...`, so I turned them into ordered lists too.

2023-04-13 19:34 UTC, merged

2023-04-13 19:34 UTC, jwokaty commented
Thanks for your contribution!